#cloud-config
package_upgrade: true
manage_etc_hosts: false

write_files:
- owner: root:root
  path: /etc/haproxy/setup.sh
  permissions: '0755'
  content: |
    #!/bin/bash
    if [ -f "/etc/haproxy.configured" ]; then
      echo "Already configured."
      exit
    fi
    masters=${1-3}
    master_prefix=${2-k8smaster}
    proxy_ip=$(ifconfig | grep 'inet[^6]' | awk '{print $2}' | grep -v '127.0.0.1')
    cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
    cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
    frontend kubernetes-frontend
        bind $proxy_ip:6443
        mode tcp
        option tcplog
        default_backend kubernetes-backend
    backend kubernetes-backend
        mode tcp
        option tcp-check
        balance roundrobin
    EOF
    for i in $(seq 1 ${masters}); do
      master="${master_prefix}${i}"
      ip=$(grep ${master} /etc/hosts | awk '{print $1}')
      cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
        server ${master} ${ip}:6443 check fall 3 rise 2
    EOF
    done
    touch /etc/haproxy.configured
    sudo systemctl restart haproxy

packages:
- net-tools
- haproxy

runcmd:
- timedatectl set-timezone America/New_York
- timedatectl set-ntp on
- systemctl stop apparmor
- systemctl disable apparmor
